# Imports

In [1]:
from pathlib import Path
import pandas as pd
from diive.core.io.files import save_parquet, load_parquet
import matplotlib.pyplot as plt

# Load main data

In [2]:
SOURCEDIR = r"../50_MERGE_DATA_FLUXES"
FILENAME = r"51.1_FLUXES_METEO_L3.2_NEE_LE_H_FN2O_FCH4.parquet"
FILEPATH = Path(SOURCEDIR) / FILENAME
maindf = load_parquet(filepath=FILEPATH)
maindf

Loaded .parquet file ..\50_MERGE_DATA_FLUXES\51.1_FLUXES_METEO_L3.2_NEE_LE_H_FN2O_FCH4.parquet (0.778 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

                     AIR_CP  AIR_DENSITY  AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  ppfd_is_meteoswiss  timesince_prec       vpd  ts_0.05_gfXG  FLAG_ts_0.05_gfXG_ISFILLED  ts_0.15_gfXG  FLAG_ts_0.15_gfXG_ISFILLED  ts_0.3_gfXG  FLAG_ts_0.3_gfXG_ISFILLED  swc_0.05_gfXG  FLAG_swc_0.05_gfXG_ISFILLED  swc_0.15_gfXG  FLAG_swc_0.15_gfXG_ISFILLED  swc_0.3_gfXG  FLAG_swc_0.3_gfXG_ISFILLED
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                              ...
2023-10-31 23:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                   1               1  0.216913      9.098388                           1     11.378627                           1    11.530369                          1      26.031988                            1      32.485023                            1     23.174337                           1
2023-11-01 00:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                   1               2  0.272054      9.154857                           1     11.409856                           1    11.225279                          1      26.032562                            1      32.299629                            1     23.271423                           1
2023-11-01 00:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                   1               3  0.257705      9.216592                           1     11.371663                           1    11.158751                          1      26.008535                            1      32.250141                            1     23.265263                           1
2023-11-01 01:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                   1               4  0.171078      9.287736                           1     11.434952                           1    11.346931                          1      26.017988                            1      32.318672                            1     23.356800                           1
2023-11-01 01:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                   1               5  0.104550      9.090844                           1     11.641592                           1    11.395833                          1      26.031649                            1      32.319527                            1     23.369452                           1
...                     ...          ...     ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                 ...             ...       ...           ...                         ...           ...                         ...          ...                        ...            ...                          ...            ...                          ...           ...                         ...
2025-06-05 21:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                   1              22  0.285270     18.565866                           1     18.817616                           1    17.117313                          1      27.877552                            1      28.465660                            1     22.620697                           1
2025-06-05 22:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                   1              23  0.289417     18.389761                           1     18.866354                           1    16.990484                          1      27.209703                            1      28.523260                            1     22.135151                           1
2025-06-05 22:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                   1              24  0.404542     18.252666                           1     18.519451                           1    17.198946                          1      26.936914                            1      28.520008                            1     22.126200                           1
2025-06-05 23:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                   1              25  0.316704     18.474943                           1     18.481504                           1    17.115162                          1      27.125645                            1      28.743135                            1     22.391455                           1
2025-06-05 23:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                   1              26  0.298935     18.036486                           1     18.276918                           1    17.127825                          1      27.204983                            1      28.781429                            1     22.422047                           1

[27985 rows x 620 columns]

# Load REddyProc output

In [3]:
SOURCEDIR = r"../60_REDDYPROC"
FILENAME = r"61.1_UstarThresholds_MDS-gapfilled_NEE-partitioned.csv"
FILEPATH = Path(SOURCEDIR) / FILENAME
reddy = pd.read_csv(FILEPATH)

# Convert timestamp to datetime and change from end to middle
reddy['TIMESTAMP_MIDDLE'] = pd.to_datetime(reddy['TIMESTAMP_END'], format='%Y-%m-%dT%H:%M:%SZ', errors='coerce') - pd.Timedelta(minutes=15)
# Drop the timestamp end
reddy.drop(columns='TIMESTAMP_END', inplace=True)
# Set the timestamp as index
reddy.set_index('TIMESTAMP_MIDDLE', inplace=True)

# Add a string to identify the reddyproc columns later
reddy.columns = [f'{c}_reddyproc' for c in reddy.columns]

reddy

                     Ustar_U16_Thres_reddyproc  Ustar_U50_Thres_reddyproc  Ustar_U84_Thres_reddyproc  NEE_U16_f_reddyproc  NEE_U50_f_reddyproc  NEE_U84_f_reddyproc  GPP_U16_f_reddyproc  GPP_U50_f_reddyproc  GPP_U84_f_reddyproc  Reco_U16_reddyproc  Reco_U50_reddyproc  Reco_U84_reddyproc  LE_f_reddyproc  H_f_reddyproc
TIMESTAMP_MIDDLE
2023-11-07 15:45:00                   0.084600                   0.106112                   0.135006             1.328996             1.406032             1.406032             0.739229             0.608764             0.672669            2.068225            2.014795            2.078701       28.859389     -11.217375
2023-11-07 16:15:00                   0.084600                   0.106112                   0.135006             1.629891             1.626907             1.630082             0.429134             0.379030             0.439855            2.059025            2.005937            2.069938       27.488270     -13.000232
2023-11-07 16:45:00                   0.084600                   0.106112                   0.135006             2.210941             2.239952             2.275597            -0.170260            -0.251680            -0.223140            2.040680            1.988271            2.052457       17.406233      -1.975767
2023-11-07 17:15:00                   0.084600                   0.106112                   0.135006             2.185616             2.205842             2.292686            -0.222090            -0.291887            -0.313837            1.963526            1.913955            1.978848       13.825620     -11.683789
2023-11-07 17:45:00                   0.084600                   0.106112                   0.135006             2.185616             2.205842             2.292686            -0.217588            -0.287550            -0.309538            1.968028            1.918292            1.983148       13.825620     -10.829124
...                                        ...                        ...                        ...                  ...                  ...                  ...                  ...                  ...                  ...                 ...                 ...                 ...             ...            ...
2025-06-04 21:45:00                   0.072883                   0.093717                   0.131747            10.578562            10.578562            10.578562            -2.093970            -1.558117            -1.515354            8.484592            9.020445            9.063208        2.365148     -37.795644
2025-06-04 22:15:00                   0.072883                   0.093717                   0.131747             9.416519             9.416519             9.416519            -1.006727            -0.474679            -0.429044            8.409792            8.941840            8.987474        3.145603     -33.579604
2025-06-04 22:45:00                   0.072883                   0.093717                   0.131747            10.095010            10.095010            10.095010            -1.624549            -1.089414            -1.046107            8.470461            9.005596            9.048903        3.778325     -38.997547
2025-06-04 23:15:00                   0.072883                   0.093717                   0.131747             8.641342             8.641342             8.641342            -0.192062             0.341996             0.386118            8.449280            8.983338            9.027459       -0.947239     -39.849475
2025-06-04 23:45:00                   0.072883                   0.093717                   0.131747             8.664543             8.664543             8.664543            -0.332127             0.195977             0.244553            8.332416            8.860520            8.909096        2.365148     -53.513862

[27617 rows x 14 columns]

# Merge

In [4]:
newcols = [c for c in reddy.columns if c not in maindf]
print("NEW VARIABLES FROM REDDYPROC:")
[print(f"+ {c}") for c in newcols]
maindf = pd.concat([maindf, reddy[newcols]], axis=1)
maindf

NEW VARIABLES FROM REDDYPROC:
+ Ustar_U16_Thres_reddyproc
+ Ustar_U50_Thres_reddyproc
+ Ustar_U84_Thres_reddyproc
+ NEE_U16_f_reddyproc
+ NEE_U50_f_reddyproc
+ NEE_U84_f_reddyproc
+ GPP_U16_f_reddyproc
+ GPP_U50_f_reddyproc
+ GPP_U84_f_reddyproc
+ Reco_U16_reddyproc
+ Reco_U50_reddyproc
+ Reco_U84_reddyproc
+ LE_f_reddyproc
+ H_f_reddyproc

                     AIR_CP  AIR_DENSITY  AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  FLAG_swc_0.3_gfXG_ISFILLED  Ustar_U16_Thres_reddyproc  Ustar_U50_Thres_reddyproc  Ustar_U84_Thres_reddyproc  NEE_U16_f_reddyproc  NEE_U50_f_reddyproc  NEE_U84_f_reddyproc  GPP_U16_f_reddyproc  GPP_U50_f_reddyproc  GPP_U84_f_reddyproc  Reco_U16_reddyproc  Reco_U50_reddyproc  Reco_U84_reddyproc  LE_f_reddyproc  H_f_reddyproc
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                              ...
2023-10-31 23:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                           1                        NaN                        NaN                        NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN                 NaN                 NaN             NaN            NaN
2023-11-01 00:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                           1                        NaN                        NaN                        NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN                 NaN                 NaN             NaN            NaN
2023-11-01 00:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                           1                        NaN                        NaN                        NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN                 NaN                 NaN             NaN            NaN
2023-11-01 01:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                           1                        NaN                        NaN                        NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN                 NaN                 NaN             NaN            NaN
2023-11-01 01:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                           1                        NaN                        NaN                        NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN                 NaN                 NaN             NaN            NaN
...                     ...          ...     ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                         ...                        ...                        ...                        ...                  ...                  ...                  ...                  ...                  ...                  ...                 ...                 ...                 ...             ...            ...
2025-06-05 21:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                           1                        NaN                        NaN                        NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN                 NaN                 NaN             NaN            NaN
2025-06-05 22:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                           1                        NaN                        NaN                        NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN                 NaN                 NaN             NaN            NaN
2025-06-05 22:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                           1                        NaN                        NaN                        NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN                 NaN                 NaN             NaN            NaN
2025-06-05 23:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                           1                        NaN                        NaN                        NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN                 NaN                 NaN             NaN            NaN
2025-06-05 23:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                           1                        NaN                        NaN                        NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN                 NaN                 NaN             NaN            NaN

[27985 rows x 634 columns]

# Export

In [5]:
filename = "71.1_FLUXES_METEO_L3.2_NEE_LE_H_FN2O_FCH4_REDDYPROC"
maindf.to_csv(f"{filename}.csv", index=True)
save_parquet(data=maindf, filename=filename)

Saved file 71.1_FLUXES_METEO_L3.2_NEE_LE_H_FN2O_FCH4_REDDYPROC.parquet (5.538 seconds).

'71.1_FLUXES_METEO_L3.2_NEE_LE_H_FN2O_FCH4_REDDYPROC.parquet'