# IMPORTS

In [1]:
from pathlib import Path
import pandas as pd
from diive.core.io.files import save_parquet, load_parquet

# LOAD DATA

In [2]:
maindf = load_parquet(filepath=r"../70_SPLIT_TREATMENTS/71.1_FLUXES_L3.3_NEE_LE_H_FN2O_FCH4_REDDYPROC_PARCELS.parquet")
gf_part = load_parquet(filepath=r"../80_GAP-FILLING/84.1_GF-FLUXES+PARTITIONED.parquet")
meteo = load_parquet(filepath=r"../10_METEO/13.1_CH-TAN_meteo_gapfilled.parquet")
management = load_parquet(filepath=r"../20_MANAGEMENT/21.1_mgmt_full_timestamp.parquet")

Loaded .parquet file ../70_SPLIT_TREATMENTS/71.1_FLUXES_L3.3_NEE_LE_H_FN2O_FCH4_REDDYPROC_PARCELS.parquet (0.689 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min
Loaded .parquet file ../80_GAP-FILLING/84.1_GF-FLUXES+PARTITIONED.parquet (0.133 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min
Loaded .parquet file ../10_METEO/13.1_CH-TAN_meteo_gapfilled.parquet (0.185 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min
Loaded .parquet file ../20_MANAGEMENT/21.1_mgmt_full_timestamp.parquet (0.083 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

# MERGE

## Gap-filled & partitioned fluxes

In [3]:
newcols = [c for c in gf_part.columns if c not in maindf]
print("NEW VARIABLES FROM FLUX PROCESSING CHAIN:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, gf_part[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ NEE_L3.3_CUT_50_QCF_gfXGBoost
++ FLAG_NEE_L3.3_CUT_50_QCF_gfXGBoost_ISFILLED
++ NEE_L3.3_CUT_50_QCF0_gfXGBoost
++ FLAG_NEE_L3.3_CUT_50_QCF0_gfXGBoost_ISFILLED
++ RECO_NT_CUT_50_gfXG_QCF
++ GPP_NT_CUT_50_gfXG_QCF
++ RECO_NT_CUT_50_gfXG_QCF0
++ GPP_NT_CUT_50_gfXG_QCF0
++ FN2O_L3.3_CUT_50_QCF_gfXGBoost_footprint
++ FLAG_FN2O_L3.3_CUT_50_QCF_gfXGBoost_footprint_ISFILLED
++ FN2O_L3.3_CUT_50_QCF_gfXGBoost_parcelA_certain
++ FN2O_L3.3_CUT_50_QCF_gfXGBoost_parcelA_all
++ FLAG_FN2O_L3.3_CUT_50_QCF_gfXGBoost_parcelA_all_ISFILLED
++ FLAG_FN2O_L3.3_CUT_50_QCF_gfXGBoost_parcelA_certain_ISFILLED
++ FN2O_L3.3_CUT_50_QCF_gfXGBoost_parcelB_certain
++ FN2O_L3.3_CUT_50_QCF_gfXGBoost_parcelB_all
++ FLAG_FN2O_L3.3_CUT_50_QCF_gfXGBoost_parcelB_all_ISFILLED
++ FLAG_FN2O_L3.3_CUT_50_QCF_gfXGBoost_parcelB_certain_ISFILLED
++ FN2O_L3.3_CUT_50_QCF0_gfXGBoost_footprint
++ FLAG_FN2O_L3.3_CUT_50_QCF0_gfXGBoost_footprint_ISFILLED
++ FN2O_L3.3_CUT_50_QCF0_gfXGBoost_parcelA_certain
++ FN2O_L3.3_CUT_50_QCF0_gfXGBoost_parcelA_all
++ FLAG_FN2O_L3.3_CUT_50_QCF0_gfXGBoost_parcelA_all_ISFILLED
++ FLAG_FN2O_L3.3_CUT_50_QCF0_gfXGBoost_parcelA_certain_ISFILLED
++ FN2O_L3.3_CUT_50_QCF0_gfXGBoost_parcelB_certain
++ FN2O_L3.3_CUT_50_QCF0_gfXGBoost_parcelB_all
++ FLAG_FN2O_L3.3_CUT_50_QCF0_gfXGBoost_parcelB_all_ISFILLED
++ FLAG_FN2O_L3.3_CUT_50_QCF0_gfXGBoost_parcelB_certain_ISFILLED
++ FCH4_L3.3_CUT_50_QCF_gfXGBoost_footprint
++ FLAG_FCH4_L3.3_CUT_50_QCF_gfXGBoost_footprint_ISFILLED
++ FCH4_L3.3_CUT_50_QCF_gfXGBoost_parcelA_certain
++ FCH4_L3.3_CUT_50_QCF_gfXGBoost_parcelA_all
++ FLAG_FCH4_L3.3_CUT_50_QCF_gfXGBoost_parcelA_all_ISFILLED
++ FLAG_FCH4_L3.3_CUT_50_QCF_gfXGBoost_parcelA_certain_ISFILLED
++ FCH4_L3.3_CUT_50_QCF_gfXGBoost_parcelB_certain
++ FCH4_L3.3_CUT_50_QCF_gfXGBoost_parcelB_all
++ FLAG_FCH4_L3.3_CUT_50_QCF_gfXGBoost_parcelB_all_ISFILLED
++ FLAG_FCH4_L3.3_CUT_50_QCF_gfXGBoost_parcelB_certain_ISFILLED
++ FCH4_L3.3_CUT_50_QCF0_gfXGBoost_footprint
++ FLAG_FCH4_L3.3_CUT_50_QCF0_gfXGBoost_footprint_ISFILLED
++ FCH4_L3.3_CUT_50_QCF0_gfXGBoost_parcelA_certain
++ FCH4_L3.3_CUT_50_QCF0_gfXGBoost_parcelA_all
++ FLAG_FCH4_L3.3_CUT_50_QCF0_gfXGBoost_parcelA_all_ISFILLED
++ FLAG_FCH4_L3.3_CUT_50_QCF0_gfXGBoost_parcelA_certain_ISFILLED
++ FCH4_L3.3_CUT_50_QCF0_gfXGBoost_parcelB_certain
++ FCH4_L3.3_CUT_50_QCF0_gfXGBoost_parcelB_all
++ FLAG_FCH4_L3.3_CUT_50_QCF0_gfXGBoost_parcelB_all_ISFILLED
++ FLAG_FCH4_L3.3_CUT_50_QCF0_gfXGBoost_parcelB_certain_ISFILLED

                     AIR_CP  AIR_DENSITY  AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  FLAG_FCH4_L3.3_CUT_50_QCF_gfXGBoost_parcelA_certain_ISFILLED  FCH4_L3.3_CUT_50_QCF_gfXGBoost_parcelB_certain  FCH4_L3.3_CUT_50_QCF_gfXGBoost_parcelB_all  FLAG_FCH4_L3.3_CUT_50_QCF_gfXGBoost_parcelB_all_ISFILLED  FLAG_FCH4_L3.3_CUT_50_QCF_gfXGBoost_parcelB_certain_ISFILLED  FCH4_L3.3_CUT_50_QCF0_gfXGBoost_footprint  FLAG_FCH4_L3.3_CUT_50_QCF0_gfXGBoost_footprint_ISFILLED  FCH4_L3.3_CUT_50_QCF0_gfXGBoost_parcelA_certain  FCH4_L3.3_CUT_50_QCF0_gfXGBoost_parcelA_all  FLAG_FCH4_L3.3_CUT_50_QCF0_gfXGBoost_parcelA_all_ISFILLED  FLAG_FCH4_L3.3_CUT_50_QCF0_gfXGBoost_parcelA_certain_ISFILLED  FCH4_L3.3_CUT_50_QCF0_gfXGBoost_parcelB_certain  FCH4_L3.3_CUT_50_QCF0_gfXGBoost_parcelB_all  FLAG_FCH4_L3.3_CUT_50_QCF0_gfXGBoost_parcelB_all_ISFILLED  FLAG_FCH4_L3.3_CUT_50_QCF0_gfXGBoost_parcelB_certain_ISFILLED
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                              ...
2023-11-06 23:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                               <NA>                                                        NaN                                         NaN                                               <NA>                                                      <NA>                                                   NaN                                               <NA>                                                    NaN                                          NaN                                               <NA>                                                       <NA>                                                          NaN                                          NaN                                               <NA>                                                       <NA>
2023-11-06 23:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                               <NA>                                                        NaN                                         NaN                                               <NA>                                                      <NA>                                                   NaN                                               <NA>                                                    NaN                                          NaN                                               <NA>                                                       <NA>                                                          NaN                                          NaN                                               <NA>                                                       <NA>
2023-11-07 00:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                               <NA>                                                        NaN                                         NaN                                               <NA>                                                      <NA>                                                   NaN                                               <NA>                                                    NaN                                          NaN                                               <NA>                                                       <NA>                                                          NaN                                          NaN                                               <NA>                                                       <NA>
2023-11-07 00:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                               <NA>                                                        NaN                                         NaN                                               <NA>                                                      <NA>                                                   NaN                                               <NA>                                                    NaN                                          NaN                                               <NA>                                                       <NA>                                                          NaN                                          NaN                                               <NA>                                                       <NA>
2023-11-07 01:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                               <NA>                                                        NaN                                         NaN                                               <NA>                                                      <NA>                                                   NaN                                               <NA>                                                    NaN                                          NaN                                               <NA>                                                       <NA>                                                          NaN                                          NaN                                               <NA>                                                       <NA>
...                     ...          ...     ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                                                ...                                                        ...                                         ...                                                ...                                                       ...                                                   ...                                                ...                                                    ...                                          ...                                                ...                                                        ...                                                          ...                                          ...                                                ...                                                        ...
2025-06-05 21:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                                  1                                                  -0.132101                                   -0.132101                                                  1                                                         1                                             -0.132101                                                  1                                              -0.006419                                    -0.006419                                                  1                                                          1                                                    -0.132101                                    -0.132101                                                  1                                                          1
2025-06-05 22:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                                  1                                                   0.091424                                    0.091424                                                  1                                                         1                                              0.091424                                                  1                                               0.433618                                     0.433618                                                  1                                                          1                                                     0.091424                                     0.091424                                                  1                                                          1
2025-06-05 22:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                                  1                                                   0.763759                                    0.763759                                                  1                                                         1                                              0.763759                                                  1                                               0.976998                                     0.976998                                                  1                                                          1                                                     0.763759                                     0.763759                                                  1                                                          1
2025-06-05 23:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                                  1                                                  -0.734866                                   -0.734866                                                  1                                                         1                                             -0.734866                                                  1                                              -0.526446                                    -0.526446                                                  1                                                          1                                                    -0.734866                                    -0.734866                                                  1                                                          1
2025-06-05 23:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                                  1                                                  -1.009158                                   -1.009158                                                  1                                                         1                                             -1.009158                                                  1                                              -0.783896                                    -0.783896                                                  1                                                          1                                                    -1.009158                                    -1.009158                                                  1                                                          1

[27698 rows x 670 columns]

## Meteo

In [ ]:
newcols = [c for c in meteo.columns if c not in maindf]
print("NEW VARIABLES FROM METEO DATA:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, meteo[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ g
++ pa
++ ppfd
++ prec
++ rh
++ swc_0.05
++ swc_0.15
++ swc_0.3
++ swc_0.05_soilvue
++ swc_0.1_soilvue
++ swc_0.2_soilvue
++ swc_0.3_soilvue
++ swc_0.4_soilvue
++ swc_0.5_soilvue
++ ta
++ ts_0.05
++ ts_0.15
++ ts_0.3
++ ts_0.05_soilvue
++ ts_0.1_soilvue
++ ts_0.2_soilvue
++ ts_0.3_soilvue
++ ts_0.4_soilvue
++ ts_0.5_soilvue
++ sw_in
++ sw_out
++ lw_in
++ lw_out
++ ta_is_meteoswiss
++ rh_is_meteoswiss
++ pa_is_meteoswiss
++ prec_is_meteoswiss
++ sw_in_is_meteoswiss
++ sw_out_is_meteoswiss
++ lw_in_is_meteoswiss
++ lw_out_is_meteoswiss
++ ppfd_is_meteoswiss
++ timesince_prec
++ vpd
++ ts_0.05_gfXG
++ FLAG_ts_0.05_gfXG_ISFILLED
++ ts_0.15_gfXG
++ FLAG_ts_0.15_gfXG_ISFILLED
++ ts_0.3_gfXG
++ FLAG_ts_0.3_gfXG_ISFILLED
++ swc_0.05_gfXG
++ FLAG_swc_0.05_gfXG_ISFILLED
++ swc_0.15_gfXG
++ FLAG_swc_0.15_gfXG_ISFILLED
++ swc_0.3_gfXG
++ FLAG_swc_0.3_gfXG_ISFILLED

                     AIR_CP  AIR_DENSITY  AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  ppfd_is_meteoswiss  timesince_prec       vpd  ts_0.05_gfXG  FLAG_ts_0.05_gfXG_ISFILLED  ts_0.15_gfXG  FLAG_ts_0.15_gfXG_ISFILLED  ts_0.3_gfXG  FLAG_ts_0.3_gfXG_ISFILLED  swc_0.05_gfXG  FLAG_swc_0.05_gfXG_ISFILLED  swc_0.15_gfXG  FLAG_swc_0.15_gfXG_ISFILLED  swc_0.3_gfXG  FLAG_swc_0.3_gfXG_ISFILLED
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                              ...
2023-10-31 23:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                   1               1  0.216913      9.098388                           1     11.378627                           1    11.530369                          1      26.031988                            1      32.485023                            1     23.174337                           1
2023-11-01 00:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                   1               2  0.272054      9.154857                           1     11.409856                           1    11.225279                          1      26.032562                            1      32.299629                            1     23.271423                           1
2023-11-01 00:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                   1               3  0.257705      9.216592                           1     11.371663                           1    11.158751                          1      26.008535                            1      32.250141                            1     23.265263                           1
2023-11-01 01:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                   1               4  0.171078      9.287736                           1     11.434952                           1    11.346931                          1      26.017988                            1      32.318672                            1     23.356800                           1
2023-11-01 01:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                   1               5  0.104550      9.090844                           1     11.641592                           1    11.395833                          1      26.031649                            1      32.319527                            1     23.369452                           1
...                     ...          ...     ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                 ...             ...       ...           ...                         ...           ...                         ...          ...                        ...            ...                          ...            ...                          ...           ...                         ...
2025-06-05 21:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                   1              22  0.285270     18.565866                           1     18.817616                           1    17.117313                          1      27.877552                            1      28.465660                            1     22.620697                           1
2025-06-05 22:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                   1              23  0.289417     18.389761                           1     18.866354                           1    16.990484                          1      27.209703                            1      28.523260                            1     22.135151                           1
2025-06-05 22:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                   1              24  0.404542     18.252666                           1     18.519451                           1    17.198946                          1      26.936914                            1      28.520008                            1     22.126200                           1
2025-06-05 23:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                   1              25  0.316704     18.474943                           1     18.481504                           1    17.115162                          1      27.125645                            1      28.743135                            1     22.391455                           1
2025-06-05 23:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                   1              26  0.298935     18.036486                           1     18.276918                           1    17.127825                          1      27.204983                            1      28.781429                            1     22.422047                           1

[27985 rows x 721 columns]

## Management

In [ ]:
newcols = [c for c in management.columns if c not in maindf]

# drop any that start with 'n_decay' or 'timesince' OR end with 'timed'
newcols = [
    c for c in newcols
    if not (c.startswith(('n_decay', 'timesince')) or c.endswith('timed'))
]

print("NEW VARIABLES FROM MANAGEMENT DATA:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, management[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ fert_parcelA
++ fert_parcelB
++ fert_min_parcelA
++ fert_min_parcelB
++ fert_org_parcelA
++ fert_org_parcelB
++ harvest
++ sowing
++ soil_preparation
++ nitrogen_fert_parcelA
++ nitrogen_fert_parcelB
++ operation
++ crop_type
++ crop

                     AIR_CP  AIR_DENSITY  AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  FLAG_swc_0.3_gfXG_ISFILLED  fert_parcelA  fert_parcelB  fert_min_parcelA  fert_min_parcelB  fert_org_parcelA  fert_org_parcelB  harvest  sowing  soil_preparation  nitrogen_fert_parcelA  nitrogen_fert_parcelB     operation  crop_type  crop
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                              ...
2023-10-17 12:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                         NaN             1             1                 0                 0                 1                 1        0       0                 0                   29.0                   29.0  manure_solid      empty   NaN
2023-10-17 12:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                         NaN             0             0                 0                 0                 0                 0        0       0                 0                    0.0                    0.0          None      empty   NaN
2023-10-17 13:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                         NaN             0             0                 0                 0                 0                 0        0       0                 0                    0.0                    0.0          None      empty   NaN
2023-10-17 13:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                         NaN             0             0                 0                 0                 0                 0        0       0                 0                    0.0                    0.0          None      empty   NaN
2023-10-17 14:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                         NaN             0             0                 0                 0                 0                 0        0       0                 0                    0.0                    0.0          None      empty   NaN
...                     ...          ...     ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                         ...           ...           ...               ...               ...               ...               ...      ...     ...               ...                    ...                    ...           ...        ...   ...
2025-06-05 21:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                         1.0             0             0                 0                 0                 0                 0        0       0                 0                    0.0                    0.0          None  grassland   3.0
2025-06-05 22:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                         1.0             0             0                 0                 0                 0                 0        0       0                 0                    0.0                    0.0          None  grassland   3.0
2025-06-05 22:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                         1.0             0             0                 0                 0                 0                 0        0       0                 0                    0.0                    0.0          None  grassland   3.0
2025-06-05 23:15:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                         1.0             0             0                 0                 0                 0                 0        0       0                 0                    0.0                    0.0          None  grassland   3.0
2025-06-05 23:45:00     NaN          NaN     NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                         1.0             0             0                 0                 0                 0                 0        0       0                 0                    0.0                    0.0          None  grassland   3.0

[28680 rows x 735 columns]

# EXPORT

In [6]:
filename = "90.1_FLUXES_METEO_MGMT"
save_parquet(data=maindf, filename=filename)
maindf.to_csv(f"{filename}.csv", index=True)

Saved file 90.1_FLUXES_METEO_MGMT.parquet (6.435 seconds).

# **End of notebook**

In [7]:
from datetime import datetime
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Finished. {dt_string}")

Finished. 2026-01-05 13:29:24